"""
ai_query_writer.py
==================
AI-powered query package content generation.

The gap between a $200–$800 query consultant and a formatting template is this:
the consultant READS the manuscript and writes the query FROM the story.
The template asks the author to fill in form fields.

This module closes that gap. It reads the actual manuscript text and generates:

  1. A HOOK SENTENCE — written from the story, not from a form
  2. A PLOT PARAGRAPH — synthesised from the narrative arc
  3. COMP TITLE SUGGESTIONS — based on genre, themes, and tone detected
  4. A SYNOPSIS DRAFT — built from chapter summaries the AI extracts
  5. A QUERY LETTER — fully written, not scaffolded

TOKEN STRATEGY
--------------
Reading the full manuscript for query generation does not require reading
every word. A consultant reads for story structure, not prose. The strategy:

  - First 2,000 words (opening): protagonist, setting, inciting event
  - Chapter titles list: structural arc
  - Last 1,000 words (closing): resolution
  - One middle chapter (500 words): stakes and midpoint conflict

Total: ~4,500–5,500 words ≈ 6,000–7,500 tokens input.
Output per call: 400–600 tokens.
Maximum calls for a full query package: 3.
"""

import re
import json
import time
import requests
from typing import List, Dict, Optional, Tuple
from dataclasses import dataclass, field

from parser import ParsedParagraph, PARA_BODY, PARA_CHAPTER, PARA_SCENE_BREAK


OPENROUTER_URL  = "https://openrouter.ai/api/v1/chat/completions"
REQUEST_TIMEOUT = 60


# ── Data Model ────────────────────────────────────────────────────────────────

@dataclass
class GeneratedQueryContent:
    """
    Content generated by reading the actual manuscript.
    Every field here is written FROM the story, not from form inputs.
    """
    # Core query letter elements
    hook_sentence:       str  = ""    # The single most important sentence
    plot_paragraph:      str  = ""    # 3–5 sentences: protagonist, conflict, stakes
    theme_sentence:      str  = ""    # The thematic core in one sentence
    protagonist_summary: str  = ""    # Who is the protagonist and what do they want?
    central_conflict:    str  = ""    # What stands in their way?
    stakes:              str  = ""    # What is lost if they fail?

    # Suggested comps (the AI identifies thematic/tonal similarities)
    comp_suggestions:    List[str] = field(default_factory=list)

    # Synopsis material
    chapter_summaries:   List[Tuple[str, str]] = field(default_factory=list)  # (title, summary)
    synopsis_draft:      str  = ""    # Full one-page synopsis draft

    # Complete query letter (fully written)
    query_letter_draft:  str  = ""

    # Metadata
    genre_detected:      str  = ""
    tone_detected:       str  = ""
    ai_powered:          bool = False
    model_used:          str  = ""
    warnings:            List[str] = field(default_factory=list)


# ── Manuscript Extractor for Query ───────────────────────────────────────────

class QueryManuscriptExtractor:
    """
    Extracts the content a query consultant would read:
    the opening, chapter structure, midpoint, and closing.
    """

    def extract(
        self, parsed: List[ParsedParagraph]
    ) -> Dict:
        body    = [p for p in parsed if p.ptype == PARA_BODY and len(p.cleaned.strip()) > 30]
        chapters = [(i, p) for i, p in enumerate(parsed) if p.ptype == PARA_CHAPTER]

        opening_text  = self._get_opening(body,    target_words=2_000)
        closing_text  = self._get_closing(body,    target_words=800)
        midpoint_text = self._get_midpoint(body,   target_words=600)
        chapter_list  = [p.cleaned for _, p in chapters]

        return {
            "opening":      opening_text,
            "midpoint":     midpoint_text,
            "closing":      closing_text,
            "chapter_list": chapter_list,
            "total_words":  sum(len(p.cleaned.split()) for p in body),
            "chapter_count": len(chapters),
        }

    def _get_opening(self, body: List[ParsedParagraph], target_words: int) -> str:
        texts, count = [], 0
        for p in body:
            texts.append(p.cleaned)
            count += len(p.cleaned.split())
            if count >= target_words:
                break
        return " ".join(texts)

    def _get_closing(self, body: List[ParsedParagraph], target_words: int) -> str:
        texts, count = [], 0
        for p in reversed(body):
            texts.insert(0, p.cleaned)
            count += len(p.cleaned.split())
            if count >= target_words:
                break
        return " ".join(texts)

    def _get_midpoint(self, body: List[ParsedParagraph], target_words: int) -> str:
        mid = len(body) // 2
        start = max(0, mid - 3)
        texts, count = [], 0
        for p in body[start:]:
            texts.append(p.cleaned)
            count += len(p.cleaned.split())
            if count >= target_words:
                break
        return " ".join(texts)


# ── AI Query Writer ───────────────────────────────────────────────────────────

class AIQueryWriter:
    """
    Reads the extracted manuscript content and generates query package material.
    """

    SYSTEM_PROMPT = """You are a professional literary agent's assistant and query consultant 
with fifteen years of experience writing query letters for published authors. You have helped 
secure representation for over 300 debut authors. You read manuscripts and write compelling 
query materials FROM the story — you never ask authors to fill in blanks.

Your writing is precise, professional, and compelling. Query letters you write result in 
full manuscript requests. You know that agents make decisions in under 60 seconds.

Respond ONLY with valid JSON. No prose outside the JSON. No markdown code fences."""

    def __init__(self, api_key: str, model: str = "mistralai/mistral-7b-instruct:free"):
        self.api_key = api_key
        self.model   = model

    # ── Call 1: Story Intelligence ────────────────────────────────────────────

    def extract_story_intelligence(
        self,
        opening:      str,
        midpoint:     str,
        closing:      str,
        chapter_list: List[str],
        genre:        str,
        word_count:   int,
    ) -> Dict:
        """
        Reads opening, midpoint, and closing to extract the core story elements
        a query consultant would identify: protagonist, conflict, stakes, theme.
        """
        chapter_display = "\n".join(f"  {i+1}. {t}" for i, t in enumerate(chapter_list[:20]))
        if len(chapter_list) > 20:
            chapter_display += f"\n  ... and {len(chapter_list)-20} more chapters"

        user_prompt = f"""Read the following sections of a {genre} manuscript ({word_count:,} words) 
and extract the story intelligence needed to write a professional query letter.

CHAPTER LIST (shows story arc):
{chapter_display}

OPENING (first ~2,000 words):
---
{opening[:3000]}
---

MIDPOINT SECTION (from middle of manuscript):
---
{midpoint[:1000]}
---

CLOSING (final ~800 words):
---
{closing[:1500]}
---

Based on ONLY what you can read from this manuscript, provide a JSON object with:

- "protagonist_name": The main character's name (exact, from the text)
- "protagonist_trait": The protagonist's most defining characteristic or situation
- "protagonist_want": What the protagonist wants or is trying to achieve
- "setting": The time period and location of the story
- "inciting_event": The specific event that kicks the story into motion (from the opening)
- "central_conflict": What stands between the protagonist and what they want
- "stakes": What the protagonist stands to lose if they fail (from midpoint/closing)
- "hook_sentence": Write the query hook sentence. ONE sentence, maximum 40 words. 
  Format: When [protagonist+trait] [inciting event], they must [central conflict] 
  or [stakes]. This must compel an agent to read the next sentence.
- "plot_paragraph": Write the query plot paragraph. 3-5 sentences covering protagonist, 
  inciting event, conflict, and stakes. Do not reveal the ending. Write in present tense.
  This should read like the plot paragraph of a published query letter.
- "theme_sentence": The thematic core of this story in one sentence.
- "tone_detected": The narrative tone (e.g. dark and lyrical, propulsive and commercial, 
  wry and character-driven, etc.)
- "genre_confirmed": The specific subgenre based on what you read
- "comp_suggestions": Array of 3 strings — suggest comparable published titles from the 
  last 3 years based on the genre, tone, and themes you detected. Format each as 
  "TITLE (YEAR) by AUTHOR — [one-sentence explanation of the comparison]"

Be specific. Use the actual character names, settings, and events from the manuscript.
Do not invent details that are not in the text."""

        return self._call_api(user_prompt) or {}

    # ── Call 2: Synopsis Draft ────────────────────────────────────────────────

    def generate_synopsis_draft(
        self,
        story_intel:  Dict,
        opening:      str,
        chapter_list: List[str],
        closing:      str,
        genre:        str,
    ) -> str:
        """
        Generates a full one-page synopsis draft from the story intelligence
        and manuscript sections.
        """
        protagonist = story_intel.get("protagonist_name", "[Protagonist]")
        conflict    = story_intel.get("central_conflict", "")
        stakes      = story_intel.get("stakes", "")
        theme       = story_intel.get("theme_sentence", "")

        chapter_arc = " → ".join(chapter_list[:12]) if chapter_list else "No chapters detected"

        user_prompt = f"""Write a professional one-page synopsis (450–550 words) for this {genre} manuscript.

STORY INTELLIGENCE:
- Protagonist: {protagonist} — {story_intel.get('protagonist_trait', '')}
- Inciting event: {story_intel.get('inciting_event', '')}
- Central conflict: {conflict}
- Stakes: {stakes}
- Theme: {theme}
- Chapter arc: {chapter_arc}

OPENING (use for setup and inciting event detail):
---
{opening[:2000]}
---

CLOSING (use for resolution — the synopsis MUST reveal the ending):
---
{closing[:1000]}
---

SYNOPSIS RULES:
1. Write in present tense, third person (even if the novel is first person)
2. Reveal the ending completely — agents require this
3. Follow story chronology
4. Character names in CAPS on first mention only
5. No marketing language — this is a plot document
6. One indented paragraph per major plot beat (opening, rising action, midpoint, 
   crisis, climax, resolution)
7. Approximately 500 words

Write the synopsis as a single JSON object with one field: "synopsis_text"
The synopsis text should contain paragraph breaks using the newline character \\n."""

        result = self._call_api(user_prompt)
        return result.get("synopsis_text", "") if result else ""

    # ── Call 3: Complete Query Letter ─────────────────────────────────────────

    def generate_query_letter(
        self,
        story_intel:  Dict,
        author_name:  str,
        title:        str,
        genre:        str,
        word_count:   int,
        series_note:  str,
        email:        str,
        phone:        str,
        address:      str,
        bio_credits:  str,
        comp_override_1: str = "",
        comp_override_2: str = "",
    ) -> str:
        """
        Generates a complete, submission-ready query letter.
        Uses AI-extracted story intelligence, not form fields.
        """
        comps = story_intel.get("comp_suggestions", [])
        comp_display = ""
        if comp_override_1:
            comp_display = comp_override_1
            if comp_override_2:
                comp_display += f" meets {comp_override_2}"
        elif comps:
            # Use first two AI suggestions, stripped of the explanation
            c1 = comps[0].split(" — ")[0] if comps else ""
            c2 = comps[1].split(" — ")[0] if len(comps) > 1 else ""
            comp_display = f"{c1} meets {c2}" if c2 else c1

        hook   = story_intel.get("hook_sentence", "")
        plot   = story_intel.get("plot_paragraph", "")
        tone   = story_intel.get("tone_detected", "")
        series = f" {series_note}." if series_note else ""
        bio    = bio_credits or f"This is {author_name}'s debut novel."

        user_prompt = f"""Write a complete, professional query letter for this manuscript.

MANUSCRIPT DETAILS:
- Title: {title}
- Author: {author_name}
- Genre: {genre}
- Word count: {word_count:,}
- Series note: {series}

STORY ELEMENTS (extracted from manuscript):
- Hook: {hook}
- Plot paragraph: {plot}
- Tone: {tone}
- Comps: {comp_display}

AUTHOR CONTACT:
- Email: {email or "[author email]"}
- Phone: {phone or "[author phone]"}
- Address: {address or "[author address]"}
- Bio/Credits: {bio}

Write the complete query letter as a JSON object with one field: "query_letter"

The letter must follow this EXACT structure (professional AAR standard):
1. Author contact block (name, email, phone, address) — left-aligned
2. Blank line
3. [Agent Name] — placeholder
4. [Agency Name] — placeholder
5. Blank line
6. Dear [Agent Name],
7. Blank line  
8. Hook paragraph (1–2 sentences using the hook provided above)
9. Plot paragraph (the plot paragraph provided above, lightly refined for flow)
10. Comps paragraph (1 sentence positioning the book with comp titles)
11. Manuscript details paragraph (title in caps, genre, word count, series note)
12. Bio paragraph (using the credits provided)
13. Closing: "Thank you for your time and consideration."
14. Sincerely, [author name]
15. A final italicised note: "[Personalise the agent salutation and the comp paragraph 
    before sending. Remove this line.]"

Write every paragraph in full. Do not use placeholders in the hook, plot, or comp 
paragraphs — those must be fully written from the story intelligence provided.
The letter should be ready to send after personalising only the agent's name."""

        result = self._call_api(user_prompt)
        return result.get("query_letter", "") if result else ""

    # ── Internal ──────────────────────────────────────────────────────────────

    def _call_api(self, user_prompt: str) -> Optional[Dict]:
        headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json",
            "HTTP-Referer": "https://author-studio-pro.local",
            "X-Title": "Author Studio Pro",
        }
        payload = {
            "model": self.model,
            "messages": [
                {"role": "system", "content": self.SYSTEM_PROMPT},
                {"role": "user",   "content": user_prompt},
            ],
            "max_tokens": 1000,
            "temperature": 0.4,
        }
        try:
            resp = requests.post(OPENROUTER_URL, headers=headers,
                                 json=payload, timeout=REQUEST_TIMEOUT)
            resp.raise_for_status()
            raw = resp.json()["choices"][0]["message"]["content"].strip()
            raw = re.sub(r"^```(?:json)?\s*", "", raw)
            raw = re.sub(r"\s*```$", "", raw).strip()
            return json.loads(raw)
        except Exception as e:
            print(f"[AIQueryWriter] API call failed: {e}")
            return None


# ── Orchestrator ──────────────────────────────────────────────────────────────

def run_ai_query_generation(
    parsed:           List[ParsedParagraph],
    api_key:          str,
    model:            str,
    author_name:      str,
    title:            str,
    genre:            str,
    word_count:       int,
    series_note:      str  = "",
    email:            str  = "",
    phone:            str  = "",
    address:          str  = "",
    bio_credits:      str  = "",
    comp_override_1:  str  = "",
    comp_override_2:  str  = "",
) -> GeneratedQueryContent:
    """
    Full orchestration: extract → story intelligence → synopsis → query letter.
    Makes exactly 3 API calls regardless of manuscript length.
    """
    extractor = QueryManuscriptExtractor()
    writer    = AIQueryWriter(api_key=api_key, model=model)
    content   = GeneratedQueryContent(ai_powered=True, model_used=model)

    # Extract strategic sections
    extracted = extractor.extract(parsed)

    # Call 1: story intelligence
    story_intel = writer.extract_story_intelligence(
        opening=extracted["opening"],
        midpoint=extracted["midpoint"],
        closing=extracted["closing"],
        chapter_list=extracted["chapter_list"],
        genre=genre,
        word_count=word_count,
    )
    time.sleep(0.5)

    if story_intel:
        content.hook_sentence       = story_intel.get("hook_sentence", "")
        content.plot_paragraph      = story_intel.get("plot_paragraph", "")
        content.theme_sentence      = story_intel.get("theme_sentence", "")
        content.protagonist_summary = story_intel.get("protagonist_name", "") + " — " + story_intel.get("protagonist_trait", "")
        content.central_conflict    = story_intel.get("central_conflict", "")
        content.stakes              = story_intel.get("stakes", "")
        content.comp_suggestions    = story_intel.get("comp_suggestions", [])
        content.genre_detected      = story_intel.get("genre_confirmed", genre)
        content.tone_detected       = story_intel.get("tone_detected", "")

    # Call 2: synopsis
    synopsis = writer.generate_synopsis_draft(
        story_intel=story_intel,
        opening=extracted["opening"],
        chapter_list=extracted["chapter_list"],
        closing=extracted["closing"],
        genre=genre,
    )
    time.sleep(0.5)
    content.synopsis_draft = synopsis

    # Call 3: complete query letter
    query_letter = writer.generate_query_letter(
        story_intel=story_intel,
        author_name=author_name,
        title=title,
        genre=genre,
        word_count=word_count,
        series_note=series_note,
        email=email,
        phone=phone,
        address=address,
        bio_credits=bio_credits,
        comp_override_1=comp_override_1,
        comp_override_2=comp_override_2,
    )
    content.query_letter_draft = query_letter

    return content
